### ISSUE TITLE
Stupides and hardest mod i've ever seen so far,

### ISSUE THREAD

**Issue by Arandomuseroninternet** [ZielonyTrojkat/Frozen-Farlands#27]
the lonely lake its just why,decrease wave or enemy please i really lose third time on this sector

**Comment by StarkillerTheGreat** [comment]
skill issue then...
lonely lake is nothing compared to idk..  Erekir itself.

**Comment by Arandomuseroninternet** [comment]
Ok...

Pada tanggal Sel, 12 Sep 2023 21.27, CY4N ***@***.***>
menulis:

**Comment by Arandomuseroninternet** [comment]
> skill issue then...
> lonely lake is nothing compared to idk..  Erekir itself.

ok
