### ISSUE TITLE
Mod causes a crash loop

### ISSUE THREAD

**Issue by epicEaston197** [ZielonyTrojkat/Frozen-Farlands#32]
When I downloaded and enabled this mod it caused a crash loop resulting in the previous instance failing to initialize and all mods being disabled

version: 146

Log [last_log.txt](https://github.com/ZielonyTrojkat/Frozen-Farlands/files/13662685/last_log.txt)

**Comment by epicEaston197** [comment]
Just updated Java and i'm experiencing the same behavior

**Comment by ZielonyTrojkat** [comment]
I dont had any other issues like that, dont know whats causing that

**Comment by epicEaston197** [comment]
Game display this then closed
the game constantly fails to initialize
![image](https://github.com/ZielonyTrojkat/Frozen-Farlands/assets/76523692/421f07d2-a3c8-4022-83dc-d470ad739a07)

**Comment by epicEaston197** [comment]
OK so I cleared all my game data and only had this mod enabled and I still experience the same issue
