### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by Up-an-Down** [ZielonyTrojkat/Frozen-Farlands#5]
No words. Just this.

![image](https://user-images.githubusercontent.com/104922829/234933398-1c2aa351-d149-4629-a618-dc72c0b66c91.png)
![image](https://user-images.githubusercontent.com/104922829/234933462-def2af83-f333-4e71-b00a-bc06245ef9ff.png)
![image](https://user-images.githubusercontent.com/104922829/234933522-2f489962-1d48-4f39-8836-532ec54ba26e.png)
![image](https://user-images.githubusercontent.com/104922829/234933613-62d5ac44-f3e1-428a-af7e-57ac47efda5a.png)
![image](https://user-images.githubusercontent.com/104922829/234933713-704da4f2-d717-477f-86a0-d09c797b8361.png)
![image](https://user-images.githubusercontent.com/104922829/234933773-47ace28d-480f-4813-9f33-b64a7b140db6.png)
![image](https://user-images.githubusercontent.com/104922829/234933823-0a9d013d-61aa-475c-923c-42177ceff72c.png)

I still want to play this mod.
Is it because I have foo client installed?

**Comment by Swirek3331** [comment]
That is main clue in my opinion.

Could you describe more of background?
Like what is written in error's message. Game version. Other mods being active.
